// flow-typed signature: 178c94250d9867b27ea8bcc029f084d1
// flow-typed version: <<STUB>>/shallow-equal_v^1.2.1/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shallow-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shallow-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shallow-equal/arrays' {
  declare module.exports: any;
}

declare module 'shallow-equal/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'shallow-equal/dist/index.esm' {
  declare module.exports: any;
}

declare module 'shallow-equal/objects' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shallow-equal/arrays/index' {
  declare module.exports: $Exports<'shallow-equal/arrays'>;
}
declare module 'shallow-equal/arrays/index.js' {
  declare module.exports: $Exports<'shallow-equal/arrays'>;
}
declare module 'shallow-equal/dist/index.cjs.js' {
  declare module.exports: $Exports<'shallow-equal/dist/index.cjs'>;
}
declare module 'shallow-equal/dist/index.esm.js' {
  declare module.exports: $Exports<'shallow-equal/dist/index.esm'>;
}
declare module 'shallow-equal/objects/index' {
  declare module.exports: $Exports<'shallow-equal/objects'>;
}
declare module 'shallow-equal/objects/index.js' {
  declare module.exports: $Exports<'shallow-equal/objects'>;
}
