// flow-typed signature: 964a77a5c551c87428abecc2eabe8ff8
// flow-typed version: <<STUB>>/@oryd/kratos-client_v^0.5.3-alpha.1/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oryd/kratos-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oryd/kratos-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oryd/kratos-client/dist/api' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/base' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist/configuration' {
  declare module.exports: any;
}

declare module '@oryd/kratos-client/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oryd/kratos-client/dist/api.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/api'>;
}
declare module '@oryd/kratos-client/dist/base.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/base'>;
}
declare module '@oryd/kratos-client/dist/configuration.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist/configuration'>;
}
declare module '@oryd/kratos-client/dist/index' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist'>;
}
declare module '@oryd/kratos-client/dist/index.js' {
  declare module.exports: $Exports<'@oryd/kratos-client/dist'>;
}
